### ISSUE TITLE
Unable to Login after Initial Setup

### ISSUE THREAD

**Issue by scottcom4** [linuxserver/docker-openvpn-as#41] opened 2018-09-13 03:30 UTC
Docker Version 17.05.0-ce Synology

docker create \
--name=openvpn-as \
-v /volume1/docker/openvpn-as/config/:/config \
-e PGID=65545 -e PUID=1043 \
-e TZ=Australia/Brisbane \
-e INTERFACE=eth0 \
--net=host --privileged \
linuxserver/openvpn-as
	
Using the above allows me to access the WebUI on port 943, however, I am unable to log in using the relevant username/password (admin/password).  The error produced is "Login Failed".

I have raised the issue on Discord, however have not received a solution.

**Comment by aptalca** [comment] 2018-09-13 03:42
I was not able to reproduce. I pulled a fresh image and created a new container and can log in just fine.

Make sure that your config folder is on a local drive and not a remote mount. You can even try without mapping a location for it to test

**Comment by scottcom4** [comment] 2018-09-13 03:57
I pulled the latest image and attempted without mapping the config and I still get "Failed Login".

**Comment by j0nnymoe** [comment] 2019-04-23 11:57
Is this still an issue?

**Comment by CygnusHyoga** [comment] 2019-05-28 20:42
I have a similar problem with login. I can login with admin/password, after I create a new admin user, login with the new user, and delete the admin user. And comment as.conf the var boot_pam_users.0=admin with #boot_pam_users.0=admin, I can't login with the new admin user, after restart the pod with the error "Failed to login"

One interesting thing, is the I create a normal user, and this user is persistent and I can login all right but is no admin.

**Comment by CHBMB** [comment] 2019-05-29 00:02
@CygnusHyoga Similar isn't necessarily the same.  If you think this is a bug with the container, can you open a new image and submit all the requested info in the template so we can test. 

Cheers.

I'm going to close this now as this container has been dramatically rewritten since the original issue was filed.

**Closed by CHBMB** 2019-05-29 00:02 UTC
