### ISSUE TITLE
Fix pam authentication issues with network mode host

### ISSUE THREAD

**Issue by doino-gretchenliev** [linuxserver/docker-openvpn-as#97] opened 2019-12-07 19:52 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

When the image is started with network mode host the web ui fails to authenticate with the pam module.

------------------------------

## Expected Behavior
It should authenticate as the container started with a bridge network.

## Steps to Reproduce
1. Docker compose setup:
```
version: "3"
services:
  openvpn:
    image: linuxserver/openvpn-as:latest
    container_name: openvpn
    volumes:
      - /docker/openvpn/config:/config:rw
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 1194:1194/udp
      - 943:943
      - 9443:9443
    network_mode: host
    environment:
      - PGID=999
      - PUID=999
      - TZ=Europe/Sofia
    privileged: true
```

## Environment
Linux 3.10.105 SMP Tue Jul 3 19:50:10 CST 2018 x86_64 GNU/Linux synology_broadwell_3617xs

## The fix
Rebuild pam module without audit:
```
RUN apt-get update && \
    apt-get -y build-dep pam && \
    export CONFIGURE_OPTS=--disable-audit && \
    cd /tmp && \
    apt-get -b source pam && \
    dpkg -i libpam-doc*.deb libpam-modules*.deb libpam-runtime*.deb libpam0g*.deb && \
    rm -rf /tmp/*
```

**Comment by thelamer** [comment] 2019-12-07 20:19
From the readme: 

```

-e INTERFACE=eth0 | With bridge networking, leave it as eth0 (or don't include at all), if host or macvlan, set it to your host's network interface, found by running ifconfig
-- | --


```

**Comment by doino-gretchenliev** [comment] 2019-12-07 20:21
The interface setting has nothing to do with the pam module.

**Comment by thelamer** [comment] 2019-12-07 20:28
You are correct ignore me

**Comment by aptalca** [comment] 2019-12-08 00:40
What exactly is the issue?

**Comment by doino-gretchenliev** [comment] 2019-12-08 00:41
> When the image is started with network mode host the web ui fails to authenticate with the pam module.

**Comment by aptalca** [comment] 2019-12-08 01:40
I guess I'm blind, totally missed that :)

Last I checked it was working fine. But granted I haven't really tested host networking in a while ever since since we added bridge networking support. I'll look into it. Thanks.

**Comment by aptalca** [comment] 2019-12-11 21:11
I am not able to reproduce any errors.

On a fresh ubuntu bionic, ran `docker run -d --rm --name=openvpn-as --cap-add=NET_ADMIN --net=host -e INTERFACE=enp1s0 linuxserver/openvpn-as` and no issues logging into the admin interface.

Can you provide more info on your environment, logs, etc.?

Thanks

**Comment by thelamer** [comment] 2019-12-11 21:16
I pointed out before the interface was not set , could this be the actual root problem ?

**Comment by aptalca** [comment] 2019-12-11 21:18
Possible. If not set, it defaults to `eth0`. Without logs, hard to tell.

**Comment by doino-gretchenliev** [comment] 2019-12-12 12:20
As I put in the issue description the OS is `synology_broadwell_3617xs `, running Linux kernel version: `Linux 3.10.105`. The issue has nothing to do with `INTERFACE` environment variable. As state above, not all linux derivatives have access to `audit` functionality of the `pam` module. However, Synology users have an even bigger issue with that image, as there is no easy way to create and configure a `tun` device, that works with this image. There is a guide on how to do it [here](https://www.reddit.com/r/synology/comments/74te0y/howto_deploy_openvpn_on_synology_using_docker/), but the VPN is still not using the device. I will not spend more time on this image, as I already did spend a significant amount of time with no luck. Feel free to close the issue or investigate it on Synology hardware. I hope those comments will help Synology users.

**Comment by aptalca** [comment] 2019-12-12 12:37
You really have not provided much info. No logs, only a statement `When the image is started with network mode host the web ui fails to authenticate with the pam module.`, which I cannot reproduce.

Also not sure why you're trying to run with host networking as opposed to bridge networking as suggested in the readme.

No one in the team has a synology device so closing this now. Feel free to reopen if you want to troubleshoot or discuss further.

**Closed by aptalca** 2019-12-12 12:37 UTC
